name: Create Cloud function 

on:
  workflow_call:
env:
  tag: ${GITHUB_REF#refs/*/}
  repository: wgall-org/functions_CICD

jobs:        
  create_function:
      name: Deploy function on Cloud 
      runs-on: ubuntu-latest
      steps:
        - name: Correct project name
          run: echo "project=$(echo ${{ github.event.repository.name }}-${{ env.tag }} | tr _ - )" >> $GITHUB_ENV
        - name: Checkout code repository
          uses: actions/checkout@v3
        - name: Authenitcate pipeline repository 
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: ${{ secrets.SA_CREDENTIALS }}
        - name: Setup pipline repository
          uses: google-github-actions/setup-gcloud@main 
          with:
            project_id: ${{ env.projectid }}
            export_default_credentials: true
        - name: Check if function is already deployed
          run: |
            echo "is_present=$(gcloud functions list | grep ${{ env.project }} | wc -l)" >> $GITHUB_ENV
        - name: Delete previous function 
          if: ${{ env.is_present == '1'}}
          run: |
            gcloud functions delete ${{ env.project }} --region europe-central2 --quiet
        - id: 'deploy'
          uses: 'google-github-actions/deploy-cloud-functions@v1'
          with:
            name: "${{env.project}}"
            runtime: 'nodejs16' 
            entry_point: main
            region: europe-central2
            credentials: ${{ secrets.SA_CREDENTIALS }}
            source_path: ./
            ingress_settings:  ALLOW_ALL
        # - name: Deploy function 
        #   working-directory: ./scripts
        #   run: |
        #     chmod 777 ../source_code.zip
        #     python3 main.py "${{env.reponame}}-${{ env.tag }}"
        